### ISSUE TITLE
How to change some colours

### ISSUE THREAD

**Issue by SCorpio121** [jeffThompson/DarkArduinoTheme#10]
Hi Jeff, im SCorpio from the blog, and i need your help.
As i said, im super nooby in arduino, and i don't want to crash something, so, i would like to change the number colours (delays...) because your dark theme helped me a lot, but the numbers still have the same colour (gray) and i would change it to yellow.
It will really help me with programation, seriously, it's extremely different to program with your theme (in my case, because it helps me differentiate parts or simply to find each part quickly).
I dealed before with some .txt codes, but in that case, i can't understand how it works.
Please could you tell me which part in the code i have to change to make the numbers have yellow colour? You will help me a lot.

Here I leave the code copied and pasted directly from the .txt file:

//FUNCTIONS COLOR 			//D35400 - ORANGE			KEYWORD1
//FUNCTIONS COLOR			//D35400 - ORANGE			KEYWORD2
//STRUCTURE COLORS 			//5E6D03 - GREEN			KEYWORD3
//VARIABLES COLOR 				//00979C - BLUE				LITERAL1

//ERROR COLOR					//A61717 - RED
//COMMENTS // COLOR			//95A5A6 - LIGHT GREY
//COMMENTS /**/ COLOR		//434F54	- DARK GREY

// GUI - STATUS
status.notice.fgcolor = //002325
status.notice.bgcolor = //404040
status.error.fgcolor = //FFFFFF
status.error.bgcolor = //E34C00
status.edit.fgcolor = //000000
status.edit.bgcolor = //F1B500
status.font = SansSerif,plain,12

// GUI - TABS
// settings for the tabs at the top
// (tab images are stored in the lib/theme folder)
header.bgcolor = //404040
header.text.selected.color = //323232
header.text.unselected.color = //3C3C3C
header.text.font = SansSerif,plain,12

// GUI - CONSOLE
console.font = Monospaced,plain,11
console.font.macosx = Monaco,plain,10
console.color = //000000
console.output.color = //eeeeee
console.error.color = //E34C00

// GUI - BUTTONS
buttons.bgcolor = //505050
buttons.status.font = SansSerif,plain,12
buttons.status.color = //ffffff

// GUI - LINESTATUS
linestatus.color = //ffffff
linestatus.bgcolor = //404040

// EDITOR - DETAILS

// foreground and background colors
editor.fgcolor = //ffffff
editor.bgcolor = //202020

// highlight for the current line
editor.linehighlight.color=//333333
// highlight for the current line
editor.linehighlight=true

// caret blinking and caret color
editor.caret.color = //a0a0a0

// color to be used for background when 'external editor' enabled
editor.external.bgcolor = //c8d2dc

// selection color
editor.selection.color = //dd8800

// area that's not in use by the text (replaced with tildes)
editor.invalid.style = //7e7e7e,bold

// little pooties at the end of lines that show where they finish
editor.eolmarkers = false
editor.eolmarkers.color = //999999

// bracket/brace highlighting
editor.brackethighlight = true
editor.brackethighlight.color = //006699

// TEXT - KEYWORDS

// FUNCTIONS
editor.keyword1.style = //d35400,bold
editor.data_type.style = //d35400,bold

// METHODS
editor.keyword2.style = //D35400,plain
editor.function.style = //d35400,plain

// STRUCTURES
editor.keyword3.style = //5E6D03,plain
editor.reserved_word.style = //5E6D03,plain

// TEXT - LITERALS

// constants & datatypes
editor.literal1.style = //006699,plain

// p5 built in variables: e.g. mouseX, width, pixels
editor.literal2.style = //00979C,plain
editor.variable.style = //00979C,plain
editor.reserved_word_2.style = //00979C,plain
editor.literal_boolean.style = //00979C,plain
editor.literal_char.style = //00979C,plain
editor.literal_string_double_quote.style = //00979C,plain
editor.preprocessor.style = //5E6D03,plain

// http://www.arduino.cc/ - GET RID OF UNDERLINE!
editor.url.style = //81A421,plain

// e.g. + - = /
editor.operator.style = //aaaaaa,plain

// ?? maybe this is for words followed by a colon
// like in case statements or goto
editor.label.style = //7e7e7e,bold

// TEXT - COMMENTS
editor.comment1.style = //aaaaaa,plain
editor.comment2.style = //aaaaaa,plain

// LINE STATUS - editor line number status bar at the bottom of the screen
linestatus.font	   = SansSerif,plain,10
linestatus.height  = 20

Wow, i have to say that the .txt file in the notebook it's just a horizontal line.
Here makes more sense to understand.
Anyways, please Jeff, help me with that.

PD. I changed every commentary sign for a double bar to not create incompatiblities

**Comment by jeffThompson** [comment]
I'm afraid trial and error is your only option. I've tried to annotate the files as best I can, but with the last few updates, the theme files for the Arduino IDE have gotten really twisted and confusing. You should also look at the XML files in here, where some colors are: https://github.com/jeffThompson/DarkArduinoTheme/tree/master/theme/syntax

**Comment by SCorpio121** [comment]
Well, Jeff, at least i understood how it works, but i could not change it.
Just because i want the yellow colour, and i don't know where i have to change.

[theme.txt](https://github.com/jeffThompson/DarkArduinoTheme/files/249465/theme.txt)

Look, i organized the the file to make it more understandable. And yes, i know how to change the colours, but i don't know where i have to replace the colour code to make the numbers of the delays yellow.
Should i try to replace the yellow colour code on every colour code and look which part changes?
It can't be that hard i mean. Anyways, thanks for all Jeff.

**Comment by jeffThompson** [comment]
Making changes is easy, but time consuming. I'd just start changing things that look likely and see what happens. You have to restart the IDE every time, though :)
