### ISSUE TITLE
Windows Installation Folder??

### ISSUE THREAD

**Issue by SalvorinFex** [jeffThompson/DarkArduinoTheme#11]
I used to use this in Windows and since, have had to wipe and re-install.

Where are these files to go in a Windows Environment?

**Comment by jeffThompson** [comment]
I don't have a Windows machine, but I think it goes in `Arduino/lib/` folder. If you find the place, can you post it here so I can update the instructions?

**Comment by SalvorinFex** [comment]
Hey Jeff, Okay that is the location:

`C:\Program Files (x86)\Arduino\lib`

Thanks for the hint  ;)

**Comment by bdavs** [comment]
You should add this to the README. It helped me, but I had to do some hunting to find it.

**Comment by jeffThompson** [comment]
Added, thanks all.
