### ISSUE TITLE
No buttons

### ISSUE THREAD

**Issue by roberto8** [jeffThompson/DarkArduinoTheme#12]
Buttons are not showing!
<img width="500" alt="screen shot 2016-08-05 at 17 56 23" src="https://cloud.githubusercontent.com/assets/7421145/17444098/15e19b30-5b36-11e6-9634-1fdc5c94aa4e.png">

**Comment by quique123** [comment]
I also didnt get any buttons.  The reason is the buttons.gif was changed to png.  If you bring out the buttons.gif from inside the GifButtons folder youll fix that.  You might want to bring the 4 sel tab and 4 unsel tab gifs as well as close, resize and newwindow gifs.

**Comment by jeffThompson** [comment]
So sorry for the slow reply! You need to update your version to 1.6.6+, which uses PNG instead of GIF. The old buttons, as @quique123 says, are available in the repo, in case you need the older Arduino IDE for some reason.
