### ISSUE TITLE
Serial Plotter not showing

### ISSUE THREAD

**Issue by Mat2095** [jeffThompson/DarkArduinoTheme#13]
When using the Serial Plotter (introduced in 1.6.6), the axis and graph are not shown.
The baud-rate-selector is shown.

Tested on Windows 7 64bit, Arduino 1.6.10 and 1.6.11.

**Comment by per1234** [comment]
It's because his theme.txt is missing the `plotting` entries: https://github.com/arduino/Arduino/blob/c1291eeddedfa270727bef5f8484e8092d1e58d8/build/shared/lib/theme/theme.txt#L39-L47

Adding this should fix your issue:
```
# GUI - PLOTTING
# color cycle created via colorbrewer2.org
plotting.bgcolor = #ffffff
plotting.color = #ffffff
plotting.graphcolor.size = 4
plotting.graphcolor.00 = #2c7bb6
plotting.graphcolor.01 = #fdae61
plotting.graphcolor.02 = #d7191c
plotting.graphcolor.03 = #abd9e9
```

**Comment by jeffThompson** [comment]
Thanks @Mat2095 for noticing this and @per1234 for the fix! Updated now.
