### ISSUE TITLE
Does not work in 2:1.0.5, found in Ubuntu 16.04

### ISSUE THREAD

**Issue by vidstige** [jeffThompson/DarkArduinoTheme#14]
I installed with `apt` on Xubuntu 16.04 and had problems with this theme. The Arduino IDE version is 2:1.0.5+dfsg2-4

**Comment by jeffThompson** [comment]
Can you post the error text or a screenshot of the message?

**Comment by vidstige** [comment]
There was no error message, but the tabs were off. Can post screenshot when I get around. (Need my work comp so will be wednesday soonest).

**Comment by GustavsR** [comment]
http://i.imgur.com/LvCBViQ.png
elementary OS Loki

**Comment by vidstige** [comment]
@jeffThompson I got the same as @GustavsR

**Comment by kartik00013** [comment]
can you tell us what procedure you had followed

**Comment by Minosaurier** [comment]
doesn't work with kubuntu aswell, version 2.1.0.5 
same as in screentshot

exactly the same as in the notes

**Comment by Minosaurier** [comment]
Linux will be in /usr/share/arduino/lib/

**Comment by jeffThompson** [comment]
Already updated from someone else in another issue, but thanks @Minosaurier!

**Comment by Minosaurier** [comment]
@jeffThompson you can fix it by converting the buttons.png to a buttons.gif
