### ISSUE TITLE
Labels and colours

### ISSUE THREAD

**Issue by stanleyseow** [jeffThompson/DarkArduinoTheme#16]
Thanks for creating this theme ... been suffering on the white background for the longest time...

Not really an issue but more of documentation ..

Which editor.xxx.style is for what ??

**Comment by jeffThompson** [comment]
Glad you like it! The styles in the Arduino IDE are super confusing and not at all documented. This theme is mostly the result of hours of trial and error. Many changes don't seem to do anything, either. I'd say try playing with the `editor.xxx.style` parameters and see. Let me know if you figure it out!

**Comment by stanleyseow** [comment]
Ok, i forked and added some documentation in the readme.md , of course, colours theme is a personal thing ...
