### ISSUE TITLE
Installing themes makes the IDE "damaged"

### ISSUE THREAD

**Issue by 0xff7** [jeffThompson/DarkArduinoTheme#17]
After replacing the theme folder in the Arduino IDE 1.8.5 on macOS High Sierra 10.13.4 and trying to launch I am given an error message saying the IDE is damaged and my only option is to move to the trash and reinstall Arduino IDE.

**Comment by jeffThompson** [comment]
Oof, sorry about that! Can you try installing the theme again and see if it breaks? I want to verify that it is an issue with the theme and not how you installed it before digging for a solution. Thanks.

**Comment by 0xff7** [comment]
Yea I don't know what happened the first time but it worked just now. Possibly was me not running the IDE before installing the theme now that I think about it. Maybe the altered files tripped up that initial verification that runs when you first launch a new program. Anyways nothing to worry about. Was a user error 🤦‍♂️
