### ISSUE TITLE
Arduino IDE "Windows Store" Installation

### ISSUE THREAD

**Issue by samuelcarreira** [jeffThompson/DarkArduinoTheme#19]
Hi there,
**Any way to install on Arduino IDE "Windows Store" version?**
I didn't found any lib folder on %appdata%\local\packages\ArduinoLLC.ArduinoIDE_mdqgnx93n4w
And I don't want to change the permissions to view the program files/windowsApps folder

**Comment by per1234** [comment]
If not possible now, this should be possible in the next release of the Arduino IDE via this feature: https://github.com/arduino/Arduino/pull/7115

Until then, just use the real Arduino IDE. You can get it by clicking either the "Windows Installer, for Windows XP and up" or "Windows ZIP file for non admin install" links on the software page:
https://www.arduino.cc/en/Main/Software
Those will work fine with Windows 10. You almost certainly don't need to use that Windows App Store abomination.

**Comment by jeffThompson** [comment]
Thanks @per1234, that seems like a good short-term solution and a great long-term one in the works! Closing this, unless @samuelcarreira can't get your "non admin install" suggestion to work.

**Comment by samuelcarreira** [comment]
Ok thank you all. I've choosed the Windows Store option because the automatic updates and good integration with OS.
I will wait for the next release ;)
