### ISSUE TITLE
External background color

### ISSUE THREAD

**Issue by marcusamargi** [jeffThompson/DarkArduinoTheme#2]
Thank you for creating the arduino theme! I just started with arduino today. One thing I've learned is that when I checked the "use external editor" preference the background changed to a different color. Perhaps this was your intention. But for me, I wanted to use an editor with vi key bindings (komodo edit) and still wanted the nice looking theme you provided when I go to verify my scripts. So, I changed line 50 in theme.txt accordingly.

Pasting here in case it helps anyone else.

editor.external.bgcolor = #222222

**Comment by angrypig7** [comment]
It seems like the background color for the external editor option isn't working very well.
Maybe code got swapped during update?
