### ISSUE TITLE
(minor) doesn't work right when preferences=>use external editor is selected...

### ISSUE THREAD

**Issue by gitcnd** [jeffThompson/DarkArduinoTheme#23]
the light background in this mode obscures everything...

**Comment by gitcnd** [comment]
Should use *actual* black, like this:-

`editor.bgcolor = #000000
`
Then this is reasonable when 'external editor' enabled

`editor.external.bgcolor = #303030
`

**Comment by jeffThompson** [comment]
Thanks @gitcnd! I have never used an external editor with Arduino, so I didn't think to test it. I've updated the color to match the IDE background color from the theme (which is not completely black, but a very dark gray). Can you test and see if this works better?
