### ISSUE TITLE
No 2x size buttons for large monitors

### ISSUE THREAD

**Issue by OpenDTG** [jeffThompson/DarkArduinoTheme#24]
On large monitors it shows the original IDE theme buttons

**Comment by jeffThompson** [comment]
@OpenDTG – so sorry, I know this issue is super old :)

Can you confirm if this is still an issue for you?

**Comment by jeffThompson** [comment]
Ok, I know this is a super old issue now, but FYI I am no longer maintaining this repo. Please see the note in the `README` file.
