### ISSUE TITLE
Install location is incorrect for 1.8.8 on OSX

### ISSUE THREAD

**Issue by alanbernstein** [jeffThompson/DarkArduinoTheme#26]
This theme works for me if I install it by putting a zip file with no top-level folder in my "sketch directory", at `~/Documents/Arduino/theme/dark.zip`

**Comment by jeffThompson** [comment]
Hmm, are you then enabling it within the IDE preferences window? It looks like this will be an easier way to install going forward, but is different than the current instructions. I'm going to close this, pending a change to that method of install.
