### ISSUE TITLE
File tree not found in Ubuntu. Same issue as that of #28.

### ISSUE THREAD

**Issue by vishalds2003** [jeffThompson/DarkArduinoTheme#29]
Hi,
I'm the same person who had opened issue #28 and now, I'm again experiencing the same issue. 
Recently, I had downgraded from 19.04 back to 18.04. Now, I have installed the Arduino IDE from the [official downloads page](https://www.arduino.cc/en/Main/Software). But now, there is no folder named arduino inside `/usr/share` .
I tried the grep command `grep -rl "theme.txt" /usr/share` since, according to you, the default arduino installation contains a file namely `theme.txt` which handles the theme of the IDE. But, ll I got back as the result were some configuration files from GRUB which were `/usr/share/doc/grub-common/copyright`. Thinking that I had given the wrong grep commands, I again repeated the search from the native GNOME file manager. And that gave me just the following result. 
![file tree](https://user-images.githubusercontent.com/50231856/58798515-74e8cc80-8620-11e9-9b92-016fe57106cd.png)

I think this really needs to be investigated @jeffThompson. This is not an issue with Ubuntu 19.04 and that's confirmed now. And oh, I had also searched for the `/opt/arduino-1.8.9-linux64/arduino-1.8.9/lib/theme` folder which was holding the theme folder the last time back inside Ubuntu 19.04. And now, inside /opt, there is no folder named Arduino... So, there is no folder there too. 

And also, when I ran the installation script back in 19.04 and now in 18.04 too, it gave some warnings related to /usr directory which were :

`Adding desktop shortcut, menu item and file associations for Arduino IDE...`
`rm: cannot remove '/usr/local/bin/arduino': No such file or directory`
`Removing symlink failed. Hope that's OK. If not then rerun as root with sudo.`
`touch: cannot touch '/root/.config/mimeapps.list': No such file or directory`
`/usr/bin/xdg-mime: 848: /usr/bin/xdg-mime: cannot create/root/.config/mimeapps.list.new:
Directory nonexistent`
Though I again tried with a `sudo ./install.sh`, it gave the same error. When I searched some sites and asked about this earlier at [Arduino Stack Exchange](https://arduino.stackexchange.com/questions/64813/installing-arduino-ide-in-the-new-ubuntu-disco-dingo)  but I didn't get an answer. 

I hope I have given enough resources for you to investigate.. And I hope you fix this soon....

**Comment by jeffThompson** [comment]
Hmm, can you try `which arduino` to see where the main executable is installed, then look around in that location?

**Comment by vishalds2003** [comment]
Nope. 
Both the file manager and grep don't give search results for which arduino...

**Comment by jeffThompson** [comment]
I see. I think the question still is about the Arduino install on Ubuntu, not an issue with this theme. I'd suggest asking on the Arduino forum (I don't have an Ubuntu machine to try this on) about where you can find the theme files. Feel free to re-open this issue if you find an answer and I can update the install instructions.

**Comment by vishalds2003** [comment]
OK. I found the solution after a long time. Now, this issue can't be reopened. And I don't want to spoil your repo by just opening new issues and increasing the number of issues for the same thing. Hence, this comment..
For Ubuntu based systems, the `theme` folder is located in the same directory which is extracted from the `.zip` file downloaded from the downloads page. 
That means, the file tree will be '/home/$USER/Downloads/arduino-x.x.x-linux64/arduino-x.x.x/lib`. Here, you'll find the theme folder which needs to be replaced. Replace it. If you have moved this folder into any other directory before running the `install.sh` script from the terminal, then your file tree will vary. Anyway, the theme folder will be inside this directory of the installation files....
