### ISSUE TITLE
Is dark serial monitor possible??

### ISSUE THREAD

**Issue by Attigliuzzo** [jeffThompson/DarkArduinoTheme#30]
Is it possible to have a dark color for the serial monitor?? thanks

**Comment by jeffThompson** [comment]
Ugh sorry – I know this issue is super old! Trying to catch up on some of these so stay tuned, but if you want to help identify where this is in the theme file, that would be a huge help!

**Comment by jeffThompson** [comment]
Sorry, I am no longer maintaining this repo. Please see the note in the `README` file.
