### ISSUE TITLE
dark theme does not work Arduino 1.8.10

### ISSUE THREAD

**Issue by pijushghosh014** [jeffThompson/DarkArduinoTheme#31]

**Comment by jishnu-jdn** [comment]
I just installed 1.8.10 and dark theme in windows 10 1903. it worked.

**Comment by pijushghosh014** [comment]
Windows 10 pro (64bit).
I didn't get any error.

**Comment by electronoob** [comment]
just installed theme on 1.8.10 without issue. in fact wanted to say thanks for this modification it rocks.

**Comment by jeffThompson** [comment]
Ok rad, thanks all! Sounds like this is working again after an Arduino update so I'm going to close this. Please open a new issue if you run into problems.
