### ISSUE TITLE
Dark theme Issues on Arduino 1.8.10

### ISSUE THREAD

**Issue by pijushghosh014** [jeffThompson/DarkArduinoTheme#32]
Dark theme does not work on Arduino version 1.8.10 (new version).
so please help me out.

**Comment by AndKe** [comment]
it does work for me, only the menu-bar remains white-ish.
try following the instructions again.

**Comment by jeffThompson** [comment]
Sounds like this is fixed with an Arduino update? I'm going to close this but please let me know if it's not fixed.
