### ISSUE TITLE
Installation instructions update for Mac

### ISSUE THREAD

**Issue by kr15uk** [jeffThompson/DarkArduinoTheme#35]
Arduino 1.8.11 on Catalina 10.15.2
Simply copied theme folder into ~/Documents/Arduino
Upon reboot pick up as default theme

Hope this helps

**Comment by jeffThompson** [comment]
Oh dang, that's rad! You just copied the folder titled `theme` right in there? Did it override an existing folder?

**Comment by kr15uk** [comment]
Correct, simple copy job.
There was no previous theme folder so no rewrites or whatsoever.
Also to roll back simply delete theme folder from your Documents/Arduino/ and reopen an app.

**Comment by DirtyEngineer** [comment]
Confirmed this also works for Windows as well.

**Comment by jeffThompson** [comment]
Sorry, been slow getting to this but hope to update this week – thanks again for pointing this out!

**Comment by kevinlekiller** [comment]
Works in Linux also, but in ~/Arduino

**Comment by ricardojlrufino** [comment]
Current installation is not user friendly. I'm improving theme installation in this pull request:
arduino/Arduino#10202

I made the build with these and other improvements and made available the link below, who can test it would be cool.
https://github.com/ricardojlrufino/Arduino/releases

**Comment by jeffThompson** [comment]
Sorry all, I am no longer maintaining this repo. Please see the note in the `README` file.
