### ISSUE TITLE
Integrate natively into the IDE

### ISSUE THREAD

**Issue by ricardojlrufino** [jeffThompson/DarkArduinoTheme#36]
Hi
I'm making some modifications and improvements to the Arduino IDE.
I wonder if you can help me with DarkTheme?
The idea is to be a native option (in preferences).

**Comment by ricardojlrufino** [comment]
https://github.com/ricardojlrufino/Arduino
Check releases for see some modifications...

And my very old pull request for autocomplete that sill in BETA
https://youtu.be/jSRuVy_fcVM?t=233

**Comment by jeffThompson** [comment]
Sorry, I am no longer maintaining this repo. Please see the note in the `README` file.
