### ISSUE TITLE
dark scrollbars, file menu bar

### ISSUE THREAD

**Issue by tab328** [jeffThompson/DarkArduinoTheme#37]
First off, this dark theme is great. But, after installing properly through the preferences, I noticed that the scrollbars, file menu bar, title bar, and splash screen all retain their blinding brightness. Maybe I'm wrong, but I'd wager those are outside the scope of any themes, and would require deeper modification of the IDE (which is a bit outside my skillset).

I did a bit of searching, but all I came up with were outdated tutorials on how to install various themes that suffered the same stark white borders. You'd think at least the windows app version would follow the windows dark theme settings but nope! Same irritating 3 sided white rectangle. That said, does anyone have any ideas? While were at it, I wouldn't mind losing the generic windows scrollbars in favor of some thinner, more modern ones.

**Comment by jeffThompson** [comment]
Sorry, I am no longer maintaining this repo. Please see the note in the `README` file.
