### ISSUE TITLE
Suggestion: How to make use of Theme selector in Arduino IDE

### ISSUE THREAD

**Issue by i0annis** [jeffThompson/DarkArduinoTheme#39]
The current instructions show users how to replace the default theme with this one, but sometimes it is handy to be able to swap between the original theme without having to go through folders etc. So after some search online I learned that you can actually use more than one theme and select it via the drop down menu in Preferences on the Arduino IDE. 

Here is how: 

> You can put the theme folder in a .zip file and place that file directly under the original theme folder. The important thing to know is that the theme must be directly in the root of the .zip file, not in a subfolder (as the pre-made themes are when you download the .zip file from GitHub). You can put as many .zip themes in the theme folder as you like and then select between them and the default theme via **File > Preferences > Theme**.   *

So my suggestion is to have a zip file called "_Dark Theme.zip_" here in the main folder, which includes all the contents of the "theme" folder. Users can then just copy the _Dark Theme.zip_ file straight into their Arduino theme folder (e.g.  _C:\Program Files (x86)\Arduino\lib\theme_  for Windows users) and select it via _Preferences_. Instructions in the README file will also be helpful. 

Another idea is if someone can make a script or installer file that can do the above installation automatically. Thoughts? 

*Source: https://forum.arduino.cc/index.php?topic=662909.0

**Comment by jeffThompson** [comment]
Sorry, I am no longer maintaining this repo. Please see the note in the `README` file.
