### ISSUE TITLE
Minor issue with preferences.txt

### ISSUE THREAD

**Issue by daviseford** [jeffThompson/DarkArduinoTheme#4]
A couple leftovers from your local development environment in preferences.txt:

last.sketch1.path=/Users/jthompson9/Desktop/Test/Test.pde
sketchbook.path=/Users/JeffThompson/Documents/Arduino

I'm not sure if these affect anything, but just wanted you to be aware.

**Comment by jeffThompson** [comment]
Ah, thanks! They should be overwritten as soon as you use Arduino.app for the first time.
