### ISSUE TITLE
Dark theme not working with Arduino 1.8.13?

### ISSUE THREAD

**Issue by dietzste** [jeffThompson/DarkArduinoTheme#43]
hey there!
I really would like to use the dark theme. Implementing seems pretty easy. However overwriting the theme folder doesn't seems to be working. Here is what I did so far:
-  installed and uninstalled Ardino IDE several times
- deleted the AppData Folder
- restarted my computer
- restarted Arduino IDE

To be fair: It does not work with the [One Dark Arduino](https://github.com/konrad91/OneDarkArduino) theme either. Arduino IDE works fine. If I open Arduino it shows the standard white theme even though I remove the standard theme folder. 

Can somebody help?

PS: I am using Windows 10

**Comment by jeffThompson** [comment]
Sorry, I am no longer maintaining this repo. Please see the note in the `README` file.
