### ISSUE TITLE
Not working under 1.6.6 (hourly build)

### ISSUE THREAD

**Issue by LuisDiazUgena** [jeffThompson/DarkArduinoTheme#6]
Hi!

I've been using this theme for a while and I love it! Thanks for all your work.

I'd tried to use it with 1.6.6 and it crash. Is there anything I can do to help you with this?

**Comment by jeffThompson** [comment]
Sorry about that! I'm using 1.6.5 and have no problems. What OS are you on? Do you get any error messages?

**Comment by LuisDiazUgena** [comment]
Hi! 

I'm using Windows 7 Professional. There is no error messages. It just start to run and the splashscreens appears, seems to do stuff and then it crash.

**Comment by jeffThompson** [comment]
Hmm, just updated and it crashes for me too. May take me a while to track this down!

**Comment by LuisDiazUgena** [comment]
If there is anything that I can do, please contact me!

**Comment by jeffThompson** [comment]
Fixed! Please let me know if this works on your computer.

**Comment by LuisDiazUgena** [comment]
It's working, thank you so much.
